# Use the official OpenJDK 21 image as the base image
FROM openjdk:21-jdk

# Set the working directory inside the container
WORKDIR /app

# Copy the Maven wrapper and the pom.xml file to the container
COPY mvnw .
COPY .mvn .mvn
COPY pom.xml .

# Copy the source code to the container
COPY src src

# Make the Maven wrapper script executable
RUN chmod +x mvnw

# Build the application using the Maven wrapper
RUN ./mvnw clean package

# Expose the port the application will run on
EXPOSE 8080

# Run the application
CMD ["java", "-jar", "target/world-0.0.1-SNAPSHOT.jar"]
